### ISSUE TITLE
SQL Error on MyBB 1.8.12 using PostgreSQL 9.6.5

### ISSUE THREAD

**Issue by kawaii** [frostschutz/MyBB-Patches#5]
I created a thread on the official MyBB support forums also regarding this:

https://community.mybb.com/thread-213092-post-1284753.html

I am using PostgreSQL as my database backend, this is the only plugin I have been unable to install for some reason.
```
SQL Error:
0 - ERROR: syntax error at or near "`" LINE 1: CREATE TABLE `mybb_patches` ^

Query:
CREATE TABLE `mybb_patches` ( pid INTEGER NOT NULL AUTO_INCREMENT, ptitle VARCHAR(100) NOT NULL, pdescription VARCHAR(200), pfile VARCHAR(150) NOT NULL, psize BIGINT NOT NULL, pdate BIGINT NOT NULL, psearch TEXT NOT NULL, pbefore TEXT, pafter TEXT, preplace INTEGER NOT NULL, pmulti INTEGER NOT NULL, pnone INTEGER NOT NULL, PRIMARY KEY (pid) )
```

**Comment by frostschutz** [comment]
try changing `case 'postgres':` to `case 'pgsql':` in patches/plugin.php, does that change anything?

**Comment by kawaii** [comment]
Yep, that worked. I've created a PR.
